[shell]
  program = "/opt/homebrew/bin/fish"
  args = ["-C", "fastfetch"]

[window]
  opacity=0.9

[font]
  normal = { family = "Monoid Nerd Font", style = "Regular" }
  bold = { family = "Monoid Nerd Font", style = "Bold" }
  italic = { family = "Monoid Nerd Font", style = 'Italic' }
  size = 16.0

[env]
  TERM = 'xterm-256color'

[colors]
  # Default colors
  [colors.primary]
    background = '0x1b182c'
    foreground = '0xcbe3e7'

  # Normal colors
  [colors.normal]
    black = '0x100e23'
    red = '0xff8080'
    green = '0x95ffa4'
    yellow = '0xffe9aa'
    blue = '0x91ddff'
    magenta = '0xc991e1'
    cyan = '0xaaffe4'
    white = '0xcbe3e7'

  # Bright colors
  [colors.bright]
    black = '0x565575'
    red = '0xff5458'
    green = '0x62d196'
    yellow = '0xffb378'
    blue = '0x65b2ff'
    magenta = '0x906cff'
    cyan = '0x63f2f1'
    white = '0xa6b3cc'
