# MinIO Client (mc) completions for fish shell

# Global flags
complete -c mc -l autocompletion -d "install auto-completion for your shell"
complete -c mc -l config-dir -s C -r -d "path to configuration folder"
complete -c mc -l quiet -s q -d "disable progress bar display"
complete -c mc -l disable-pager -l dp -d "disable mc internal pager"
complete -c mc -l no-color -d "disable color theme"
complete -c mc -l json -d "enable JSON lines formatted output"
complete -c mc -l debug -d "enable debug output"
complete -c mc -l resolve -r -d "resolves HOST[:PORT] to an IP address"
complete -c mc -l insecure -d "disable SSL certificate verification"
complete -c mc -l limit-upload -r -d "limits uploads to a maximum rate"
complete -c mc -l limit-download -r -d "limits downloads to a maximum rate"
complete -c mc -l custom-header -s H -r -d "add custom HTTP header"
complete -c mc -l help -s h -d "show help"
complete -c mc -l version -s v -d "print the version"

# Commands
complete -c mc -f -n __fish_use_subcommand -a alias -d "manage server credentials in configuration file"
complete -c mc -f -n __fish_use_subcommand -a admin -d "manage MinIO servers"
complete -c mc -f -n __fish_use_subcommand -a anonymous -d "manage anonymous access to buckets and objects"
complete -c mc -f -n __fish_use_subcommand -a batch -d "manage batch jobs"
complete -c mc -f -n __fish_use_subcommand -a cp -d "copy objects"
complete -c mc -f -n __fish_use_subcommand -a cat -d "display object contents"
complete -c mc -f -n __fish_use_subcommand -a cors -d "manage bucket CORS configuration"
complete -c mc -f -n __fish_use_subcommand -a diff -d "list differences between two buckets"
complete -c mc -f -n __fish_use_subcommand -a du -d "summarize disk usage recursively"
complete -c mc -f -n __fish_use_subcommand -a encrypt -d "manage bucket encryption config"
complete -c mc -f -n __fish_use_subcommand -a event -d "manage object notifications"
complete -c mc -f -n __fish_use_subcommand -a find -d "search for objects"
complete -c mc -f -n __fish_use_subcommand -a get -d "get s3 object to local"
complete -c mc -f -n __fish_use_subcommand -a head -d "display first 'n' lines of an object"
complete -c mc -f -n __fish_use_subcommand -a ilm -d "manage bucket lifecycle"
complete -c mc -f -n __fish_use_subcommand -a idp -d "manage MinIO IDentity Provider server configuration"
complete -c mc -f -n __fish_use_subcommand -a license -d "license related commands"
complete -c mc -f -n __fish_use_subcommand -a legalhold -d "manage legal hold for object(s)"
complete -c mc -f -n __fish_use_subcommand -a ls -d "list buckets and objects"
complete -c mc -f -n __fish_use_subcommand -a mb -d "make a bucket"
complete -c mc -f -n __fish_use_subcommand -a mv -d "move objects"
complete -c mc -f -n __fish_use_subcommand -a mirror -d "synchronize object(s) to a remote site"
complete -c mc -f -n __fish_use_subcommand -a od -d "measure single stream upload and download"
complete -c mc -f -n __fish_use_subcommand -a ping -d "perform liveness check"
complete -c mc -f -n __fish_use_subcommand -a pipe -d "stream STDIN to an object"
complete -c mc -f -n __fish_use_subcommand -a put -d "upload an object to a bucket"
complete -c mc -f -n __fish_use_subcommand -a quota -d "manage bucket quota"
complete -c mc -f -n __fish_use_subcommand -a rm -d "remove object(s)"
complete -c mc -f -n __fish_use_subcommand -a retention -d "set retention for object(s)"
complete -c mc -f -n __fish_use_subcommand -a rb -d "remove a bucket"
complete -c mc -f -n __fish_use_subcommand -a replicate -d "configure server side bucket replication"
complete -c mc -f -n __fish_use_subcommand -a ready -d "checks if the cluster is ready or not"
complete -c mc -f -n __fish_use_subcommand -a sql -d "run sql queries on objects"
complete -c mc -f -n __fish_use_subcommand -a stat -d "show object metadata"
complete -c mc -f -n __fish_use_subcommand -a support -d "support related commands"
complete -c mc -f -n __fish_use_subcommand -a share -d "generate URL for temporary access to an object"
complete -c mc -f -n __fish_use_subcommand -a tree -d "list buckets and objects in a tree format"
complete -c mc -f -n __fish_use_subcommand -a tag -d "manage tags for bucket and object(s)"
complete -c mc -f -n __fish_use_subcommand -a undo -d "undo PUT/DELETE operations"
complete -c mc -f -n __fish_use_subcommand -a update -d "update mc to latest release"
complete -c mc -f -n __fish_use_subcommand -a version -d "manage bucket versioning"
complete -c mc -f -n __fish_use_subcommand -a watch -d "listen for object notification events"
