# See https://wiki.hyprland.org/Configuring/Keywords/

$terminal = ghostty
$fileManager = thunar
$menu = rofi -show drun
$browser = firefox

$mainMod = SUPER

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
